### ISSUE TITLE
not build

### ISSUE THREAD

**Issue by fredcox** [NtsCiccio/react-electron#3]
Error in npm run pack-win 

  • writing effective config file=dist\builder-effective-config.yaml
Error: Unresolved node modules: typescript, sass, fibers
    at C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\util\packageDependencies.ts:112:21
From previous event:
    at Collector.resolveUnresolvedHoisted (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\util\packageDependencies.ts:88:81)
    at C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\util\packageDependencies.ts:83:18
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at Collector.collect (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\util\packageDependencies.ts:76:28)    at C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\util\packageDependencies.ts:47:44
    at Generator.next (<anonymous>)
    at _getProductionDependencies (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\out\util\packageDependencies.js:92:37)
    at getProductionDependencies (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\out\util\packageDependencies.js:83:37)
    at Lazy.<anonymous> (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\packager.ts:138:24)
    at Generator.next (<anonymous>)
    at Lazy.get value [as value] (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\lazy-val\src\main.ts:18:25)
    at C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\out\util\yarn.js:166:90
From previous event:
    at _getProductionDependencies (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\out\util\packageDependencies.js:92:37)
    at getProductionDependencies (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\out\util\packageDependencies.js:83:37)
    at Lazy.<anonymous> (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\packager.ts:138:24)
    at Generator.next (<anonymous>)
From previous event:
    at Lazy.get value [as value] (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\lazy-val\src\main.ts:18:25)
    at C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\out\util\yarn.js:166:90
    at Generator.next (<anonymous>)
From previous event:
    at _rebuild (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\util\yarn.ts:179:5)
    at rebuild (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\out\util\yarn.js:163:19)
    at C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\util\yarn.ts:20:11
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at _installOrRebuild (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\out\util\yarn.js:71:28)
    at installOrRebuild (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\out\util\yarn.js:55:28)
    at C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\packager.ts:509:13
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\packager.ts:470:70) 
    at C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\packager.ts:420:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\packager.ts:396:24)
    at C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at C:\Users\fredc\Documents\Projetos\react-electron\node_modules\graceful-fs\graceful-fs.js:144:16
    at C:\Users\fredc\Documents\Projetos\react-electron\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:155:23)
From previous event:
    at Packager._build (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\packager.ts:335:133)
    at C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at Packager.build (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (C:\Users\fredc\Documents\Projetos\react-electron\node_modules\electron-builder\src\builder.ts:228:10)
    at C:\Users\fredc\Documents\Projetos\react-electron\node_modules\electron-builder\src\cli\cli.ts:49:19
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react@0.1.0 pack-lnx: `npm run preelectron-pack && build -l`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react@0.1.0 pack-lnx script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fredc\AppData\Roaming\npm-cache\_logs\2020-05-21T14_28_47_979Z-debug.log

**Comment by NtsCiccio** [comment]
thanks for the feedback, i'll fix it soon as possible

**Comment by NtsCiccio** [comment]
@fredcox i have fix the issue, please pull the new code, delete the node_modules and and launch npm install. let me know if you have problem
